name: Build packages

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.pakgs }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - mipsel_24kc
          - aarch64_cortex-a53
        SDK:
          - openwrt-25.12
        pakgs:
          - luci-app-msd_lite
          - luci-app-ddns-go
          - luci-theme-argon

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 清理旧构建产物
      - name: Clean up
        run: rm -rf bin/*

      - name: Building packages ${{ matrix.pakgs }}
        uses: sbwml/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.SDK }}
          FEEDNAME: packages_ci
          PACKAGES: ${{ matrix.pakgs }}
          NO_REFRESH_CHECK: true
          V: s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.SDK }}-${{ github.run_id }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.apk

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "bin/packages/${{ matrix.arch }}/packages_ci/*.apk"
